apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx 
    name: webserve
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir  
    resources: 
      limits:
         cpu: "1"
         memory: "128Mi"  
      requests:
         cpu: "0.5"
         memory: "64Mi" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi

